[package]
name = "chuckfmt"
version = "0.2.2"
edition = "2024"
license = "MIT"
description = "A fast code formatter => ChucK programming language"
repository = "https://github.com/aik2mlj/chuckfmt"
keywords = ["chuck", "formatter", "cli"]

[dependencies]
lazy-regex = "3"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
# panic = "abort"
opt-level = "z"

